### ISSUE TITLE
problem during creating new thread

### ISSUE THREAD

**Issue by amitsavla** [brunnopleffken/addictive-community#124]
![image](https://cloud.githubusercontent.com/assets/20124013/23628834/b584848e-02db-11e7-815e-381ff927ab21.png)

its shown like an error when creating new thread

**Comment by brunnopleffken** [comment]
Hello @amitsavla 

Yeah, this is related to #121.
Version 0.12 now uses the embedded PHP transliterator to convert diacritics (ó, ã, ü, ø, etc.) to ASCII characters, but it seems a little unstable. The [PHP official docs](http://php.net/manual/en/class.transliterator.php) shows it works with PHP 5.4 or later and the PECL intl is embedded since 5.2, but it needs further investigation.

Which PHP version are you using?

**Comment by brunnopleffken** [comment]
Since this is the 2nd report about the same issue, I checked this as High Priority issue, as it doesn't seems like a misconfigured environment.

An update fixing this will be released this week!

**Comment by brunnopleffken** [comment]
@amitsavla 
I sent a commit changing this. It's not released yet, you must use the _'development'_ branch.
Can you perform some tests?

**Comment by amitsavla** [comment]
sure, i ll.


Thanks & Regards,
Amit Savla

Phone :+91 8767353567
Email :amit_savla@outlook.com

________________________________

**Comment by brunnopleffken** [comment]
Fixed in v0.12.1
