### ISSUE TITLE
Set the default language.

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#54]
I wanted to change the default language.
But this is not possible in Admin CP.
I do not remember if it can be set during Install.

Default language is what Guests will see
and is what members have from beginning.

Good thing you have only english in Admin CP.
This makes it easier to refer when there is issue and question.

**Comment by brunnopleffken** [comment]
There's already a configuration in database for it: `c_config.language_default_set`. Changing this field will change de default language that guests will see and the initial language setting for new members.

But I think there isn't any option in Admin CP to change it.
It's quite easy and I'll implement this today!


*About not translating the Admin CP, there's two reasons: first, is the one you told, it makes easier to solve other member's issues due to its more technical nature; the second is, there's more dictionary indexes (the `$t[]` stuff) in Admin CP than in the community itself, and I'm always changing some things under the hood: new settings, fixes, better labeled fields, notifications, etc., making it harder to maintain.*

**Comment by halojoy** [comment]
I think also you should add that setting in install.
The default language.
In my forum software the default language is only in the config.php from the installation.
To change default language I have to edit a setting in config.php.
Also the default theme is set in config.php

**Comment by brunnopleffken** [comment]
Good idea! Some settings, like community name and base URL, are saved in `c_config` right when creating the database, so set the default language together with it is easy as pie!

I could also add a field to set the default timezone (currently is set to UTC and you must change it manually in Admin CP in General > Date/Time). Although I could auto-detect the timezone using JavaScript during installation I don't completely rely on it (e.g. DST settings).

**Comment by brunnopleffken** [comment]
Both ideas are now implemented:
- Change the default language set in Admin CP (General > Community);
- Set the initial timezone and language settings during installation.

;)

**Comment by halojoy** [comment]
Great!
I will check it out. I always  update my pages after you have committed.
I close this issue.

**Comment by halojoy** [comment]
This is how I did dropdown of language in install:

foreach(scandir('../lang') as $string){
	preg_match("@^lang_(.+)\.php$@",$string, $match);
	if(count($match)==2)
		$languages[] = $match[1];
}
	
echo '<select name="language">'."\n";
foreach($languages as $lang){
	echo '<option value="'.$lang.'">'.$lang.'</option>'."\n";
}
echo '</select><br />'."\n";
