### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by zalexstudios** [brunnopleffken/addictive-community#74]
Russian symbol not allowed! It's Bad!

**Comment by brunnopleffken** [comment]
When does this happen? When posting a new thread or something?
I believe both MySQL and PHP are set as UTF-8.

**Comment by zalexstudios** [comment]
Creat new thread and give name in Russian lng for ex: "Пробная тема"
http://bb.metaldetector38.ru/thread/3-Пробная-тема
Link don't open!
I see this:
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

**Comment by brunnopleffken** [comment]
Well, now the URL should allow Unicode characters.
Can you update your files and perform a test?

BTW, thanks for the testing! I wasn't able to make deep tests when using non-latin characters... Your tests are being very helpful to make Addictive Community even better!

**Comment by zalexstudios** [comment]
1. name of title thread in russian work OK!
Next problem:
For ex: Poll 
error:
Be or not to beOS
 Yes(u0414u0430)
 No(u041du0435u0442)
 Maybe(u041cu043eu0436u0435u0442 u0431u044bu0442u044c)
After the English words written Russian. Displays like that!

**Comment by brunnopleffken** [comment]
Checking this out!

**Comment by brunnopleffken** [comment]
Done! I believe everything is working fine with Unicode + polls!

This happened because Addictive Community uses the more reliable `json_encode()` and `json_decode()` instead of `serialize/unserialize`, so we must set a flag manually to encode multibyte characters... Weird, but it's PHP, everything may happen. :stuck_out_tongue: 

_Unfortunately, it's a **breaking change and drops the PHP 5.3 support** in favor of a better Unicode/locale support when dealing with data. Although this bug is fixed and we can now use the "newer" PHP features, I'm still evaluating other options._

**Comment by zalexstudios** [comment]
Poll working! Ok! Thank! Go a head! Waiting stable release!!!
