### ISSUE TITLE
Bottomline in page. Change in main.css

### ISSUE THREAD

**Issue by halojoy** [brunnopleffken/addictive-community#94]
I use 0.10.0.
There is an issue with the last row at bottom.
Suggested fix in main.css:
Change
.row { display: flex; flex-wrap: wrap; margin-left: -10px; margin-right: -10px; }
to
.row { display: flex; flex-wrap: wrap; margin-left: 10px; margin-right: 10px; }

**Comment by brunnopleffken** [comment]
You're talking about the copyright bar? Because everything left is working fine. Although there's no issue here, I checked the CSS for the `#footer` selector to keep my mind clean. I found and removed these lines:

```css
overflow: auto;
padding: 8px;
```

I suppose this "padding" were messing up everything after I moved the grid system to flexbox with its own margins and paddings. Can you pull the changes and check?
